name: ssg_env
channels:
  - defaults
dependencies:
  - pip:
    - python==3.8.5
    - black==21.10b0
    - flake8==4.0.1
    - pre-commit==2.15.0
    - pytest==6.2.5
    - coverage==6.1.2

